version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=your_jwt_secret
      - DB_URL=postgres://postgres:postgres@postgres:5432/potom?sslmode=disable
    depends_on:
      - migrate

  migrate:
    image: golang:1.23
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir sql/schema postgres postgres://postgres:postgres@postgres:5432/potom?sslmode=disable up"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=potom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: